### ISSUE TITLE
Crash on launch [WSL]

### ISSUE THREAD

**Issue by urgentx** [miguelmota/cointop#172]
App crashes on first launch with: 

```
panic: open /tmp/cointop.log: The system cannot find the path specified.

goroutine 1 [running]:
github.com/miguelmota/cointop/cointop.(*Cointop).initlog(0xc00025a820)
        C:/Users/barco/go/pkg/mod/github.com/miguelmota/cointop@v1.6.8/cointop/debug.go:13 +0xa6
github.com/miguelmota/cointop/cointop.NewCointop(0xc000109c98)
        C:/Users/barco/go/pkg/mod/github.com/miguelmota/cointop@v1.6.8/cointop/cointop.go:293 +0xe25
github.com/miguelmota/cointop/cmd/commands.RootCmd.func1(0xc000240c80, {0xe5b2e6, 0x0, 0x0})
        C:/Users/barco/go/pkg/mod/github.com/miguelmota/cointop@v1.6.8/cmd/commands/root.go:93 +0x425
github.com/spf13/cobra.(*Command).execute(0xc000240c80, {0xc000046200, 0x0, 0x0})
        C:/Users/barco/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000240c80)
        C:/Users/barco/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/barco/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/miguelmota/cointop/cmd/commands.Execute()
        C:/Users/barco/go/pkg/mod/github.com/miguelmota/cointop@v1.6.8/cmd/commands/cmd.go:22 +0x13a
main.main()
        C:/Users/barco/go/pkg/mod/github.com/miguelmota/cointop@v1.6.8/main.go:8 +0x17
```

**Comment by urgentx** [comment]
Fixed by creating a /tmp directory.
