### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by matthiasbeyer** [miguelmota/cointop#32]

**Comment by matthiasbeyer** [comment]
Hoops, missing the backtrace:

![2019-05-19-151311_1920x1080_scrot](https://user-images.githubusercontent.com/427866/57982672-ca31b500-7a48-11e9-84dd-9a2fb6edc314.png)

**Comment by matthiasbeyer** [comment]
screenshot because I cannot even copy the error output because the terminal is completely trashed.

**Comment by JacobTDC** [comment]
You can log the backtrace to a file by using `make` and then `./main 2> error.log`, and then type `reset` to clear the term and fix it (assuming you have `ncurses-utils` or it is built-in).

**Comment by nitper** [comment]
Installed today - same issue for me.

```
fatal error: concurrent map iteration and map write

goroutine 40 [running]:
runtime.throw(0x81a0d5, 0x26)
        /usr/lib/go/src/runtime/panic.go:617 +0x72 fp=0xc0006119d0 sp=0xc0006119a0 pc=0x42d352
runtime.mapiternext(0xc000254d80)
        /usr/lib/go/src/runtime/map.go:860 +0x597 fp=0xc000611a58 sp=0xc0006119d0 pc=0x410307
runtime.mapiterinit(0x790900, 0xc0001521b0, 0xc000254d80)
        /usr/lib/go/src/runtime/map.go:850 +0x1c9 fp=0xc000611a78 sp=0xc000611a58 pc=0x40fc79
reflect.mapiterinit(0x790900, 0xc0001521b0, 0xc0001ca240)
        /usr/lib/go/src/runtime/map.go:1343 +0x54 fp=0xc000611aa8 sp=0xc000611a78 pc=0x411194
reflect.Value.MapKeys(0x790900, 0xc0001521b0, 0x15, 0x7fb101, 0x403aa4, 0xc000611c30)
        /usr/lib/go/src/reflect/value.go:1138 +0xc4 fp=0xc000611b20 sp=0xc000611aa8 pc=0x482fe4
encoding/gob.(*Encoder).encodeMap(0xc00044dc20, 0xc00044dc58, 0x790900, 0xc0001521b0, 0x15, 0x8281e8, 0xc0004fa3b0, 0x0, 0x1)
        /usr/lib/go/src/encoding/gob/encode.go:371 +0xf2 fp=0xc000611bc0 sp=0xc000611b20 pc=0x55bf32
encoding/gob.encOpFor.func3(0xc0005806c0, 0xc0001ca280, 0x790900, 0xc0001521b0, 0x15)
        /usr/lib/go/src/encoding/gob/encode.go:571 +0xa7 fp=0xc000611c40 sp=0xc000611bc0 pc=0x566d17
encoding/gob.(*Encoder).encodeSingle(0xc00044dc20, 0xc00044dc58, 0xc00047b860, 0x790900, 0xc0001521b0, 0x15)
        /usr/lib/go/src/encoding/gob/encode.go:301 +0x185 fp=0xc000611c98 sp=0xc000611c40 pc=0x55b575
encoding/gob.(*Encoder).encode(0xc00044dc20, 0xc00044dc58, 0x790900, 0xc0001521b0, 0x15, 0xc00016a2c0)
        /usr/lib/go/src/encoding/gob/encode.go:703 +0x182 fp=0xc000611d08 sp=0xc000611c98 pc=0x55f032
encoding/gob.(*Encoder).EncodeValue(0xc00044dc20, 0x790900, 0xc0001521b0, 0x15, 0x0, 0x0)
        /usr/lib/go/src/encoding/gob/encoder.go:251 +0x3aa fp=0xc000611da8 sp=0xc000611d08 pc=0x56063a
encoding/gob.(*Encoder).Encode(0xc00044dc20, 0x790900, 0xc0001521b0, 0x4, 0xc0004a44b0)
        /usr/lib/go/src/encoding/gob/encoder.go:176 +0xa6 fp=0xc000611df8 sp=0xc000611da8 pc=0x560076
github.com/miguelmota/cointop/cointop/common/filecache.serialize(0x790900, 0xc0001521b0, 0x0, 0x0, 0x30, 0xc0004a4450, 0x2b)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/common/filecache/filecache.go:115 +0x6d fp=0xc000611e38 sp=0xc000611df8 pc=0x56b17d
github.com/miguelmota/cointop/cointop/common/filecache.Set(0xc0003eab20, 0x19, 0x790900, 0xc0001521b0, 0x4e94914f0000, 0x0, 0x0)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/common/filecache/filecache.go:28 +0x287 fp=0xc000611f10 sp=0xc000611e38 pc=0x56a617
github.com/miguelmota/cointop/cointop.(*Cointop).updateCoins(0xc0000f7500, 0x0, 0x0)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/list.go:41 +0x2ad fp=0xc000611fb0 sp=0xc000611f10 pc=0x728e9d
github.com/miguelmota/cointop/cointop.(*Cointop).layout.func3(0xc0000f7500)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/layout.go:79 +0x2b fp=0xc000611fd8 sp=0xc000611fb0 pc=0x735d7b
runtime.goexit()
        /usr/lib/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000611fe0 sp=0xc000611fd8 pc=0x459991
created by github.com/miguelmota/cointop/cointop.(*Cointop).layout
        /home/user/go/src/github.com/miguelmota/cointop/cointop/layout.go:78 +0x546

goroutine 1 [select]:
github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop(0xc00023e000, 0xc00023e000, 0x0)
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui/gui.go:371 +0x17b
github.com/miguelmota/cointop/cointop.(*Cointop).Run(0xc0000f7500)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/cointop.go:330 +0x23d
github.com/miguelmota/cointop/cmd.Run()
        /home/user/go/src/github.com/miguelmota/cointop/cmd/cointop.go:36 +0x60a
main.main()
        /home/user/go/src/github.com/miguelmota/cointop/main.go:8 +0x20

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        /usr/lib/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/lib/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/lib/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 34 [select]:
github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go.Init.func1()
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go/api.go:95 +0x332
created by github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go.Init
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go/api.go:92 +0x739

goroutine 9 [select]:
github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc00014e130, 0xc000027dc0)
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0xd5
created by github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache.runJanitor
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xa9

goroutine 36 [select]:
github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go/api.go:339 +0x22e
github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc00023e000)
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui/gui.go:354 +0x30
created by github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop
        /home/user/go/src/github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui/gui.go:352 +0x57

goroutine 42 [select]:
github.com/miguelmota/cointop/cointop.(*Cointop).intervalFetchData.func1(0xc0000f7500)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/layout.go:191 +0xa9
created by github.com/miguelmota/cointop/cointop.(*Cointop).intervalFetchData
        /home/user/go/src/github.com/miguelmota/cointop/cointop/layout.go:189 +0x3f

goroutine 50 [sleep]:
runtime.goparkunlock(...)
        /usr/lib/go/src/runtime/proc.go:307
time.Sleep(0x3b9aca00)
        /usr/lib/go/src/runtime/time.go:105 +0x159
github.com/miguelmota/cointop/cointop/common/api/impl/coingecko.(*Service).GetAllCoinData.func1(0xc000088060, 0xc000010638, 0xc000017190, 0x3)
        /home/user/go/src/github.com/miguelmota/cointop/cointop/common/api/impl/coingecko/coingecko.go:111 +0x11a
created by github.com/miguelmota/cointop/cointop/common/api/impl/coingecko.(*Service).GetAllCoinData
        /home/user/go/src/github.com/miguelmota/cointop/cointop/common/api/impl/coingecko/coingecko.go:106 +0x5d

goroutine 15 [select]:
net/http.(*persistConn).writeLoop(0xc0002c4120)
        /usr/lib/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1358 +0xb0d

goroutine 14 [IO wait]:
internal/poll.runtime_pollWait(0x7f569c02df08, 0x72, 0xffffffffffffffff)
        /usr/lib/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc0002ba198, 0x72, 0x2e00, 0x2e92, 0xffffffffffffffff)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/lib/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002ba180, 0xc0001ce000, 0x2e92, 0x2e92, 0x0, 0x0, 0x0)
        /usr/lib/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0002ba180, 0xc0001ce000, 0x2e92, 0x2e92, 0x203000, 0x41525f, 0xc000177800)
        /usr/lib/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00018e0d8, 0xc0001ce000, 0x2e92, 0x2e92, 0x0, 0x0, 0x0)
        /usr/lib/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00027c140, 0xc0001ce000, 0x2e92, 0x2e92, 0xb33e20, 0x7f569fa89728, 0xc00026b938)
        /usr/lib/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc00015acd8, 0x88cf40, 0xc00027c140, 0x40b0b5, 0x7a0600, 0x7f1060)
        /usr/lib/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc00015aa80, 0x88d280, 0xc00018e0d8, 0x5, 0xc00018e0d8, 0x203000)
        /usr/lib/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc00015aa80, 0x829000, 0xc00015abb8, 0xc00026bb88)
        /usr/lib/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/lib/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc00015aa80, 0xc0005d2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc0002c4120, 0xc0005d2000, 0x1000, 0x1000, 0xc00026bc88, 0x406835, 0xc0005d4000)
        /usr/lib/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0002547e0)
        /usr/lib/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0002547e0, 0x1, 0x0, 0x0, 0x1, 0xc000022200, 0x0)
        /usr/lib/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc0002c4120)
        /usr/lib/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
        /usr/lib/go/src/net/http/transport.go:1357 +0xae8

goroutine 64 [runnable]:
github.com/miguelmota/cointop/cointop.(*Cointop).processCoins.func1()
        /home/user/go/src/github.com/miguelmota/cointop/cointop/list.go:119
created by time.goFunc
        /usr/lib/go/src/time/sleep.go:169 +0x44
```

**Comment by matthiasbeyer** [comment]
Thanks for your participation, I did not have the time to re-try and log the stderr output.

**Comment by oliverkane** [comment]
Hi there. I also get the same behavior.  The issue doesn't happen right away.  The app starts up, and after about a second or two, the app crashes back to the terminal from which I started it.  If it gets into this state, I cannot see any new text in the terminal, but I can execute commands.  The shell will have a strange color at times as well. Text is not select-able.  

Would love to help contribute, but I can't make hide or tails of this one.

Ubuntu  19.04.  OS is about 10 hours old. Installed the latest Go based on instructions linked from LND's repository. 
```
fatal error: concurrent map iteration and map write

goroutine 9 [running]:
runtime.throw(0x8190d5, 0x26)
	/usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc0004959d0 sp=0xc0004959a0 pc=0x42d242
runtime.mapiternext(0xc0000be4e0)
	/usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc000495a58 sp=0xc0004959d0 pc=0x4101f7
runtime.mapiterinit(0x78f900, 0xc00019e1b0, 0xc0000be4e0)
	/usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc000495a78 sp=0xc000495a58 pc=0x40fb69
reflect.mapiterinit(0x78f900, 0xc00019e1b0, 0xc0006da080)
	/usr/local/go/src/runtime/map.go:1343 +0x54 fp=0xc000495aa8 sp=0xc000495a78 pc=0x411084
reflect.Value.MapKeys(0x78f900, 0xc00019e1b0, 0x15, 0x7fa101, 0x403994, 0xc000495c30)
	/usr/local/go/src/reflect/value.go:1138 +0xc4 fp=0xc000495b20 sp=0xc000495aa8 pc=0x482ed4
encoding/gob.(*Encoder).encodeMap(0xc00038a1e0, 0xc00038a218, 0x78f900, 0xc00019e1b0, 0x15, 0x8271e8, 0xc0002d64b0, 0x0, 0x1)
	/usr/local/go/src/encoding/gob/encode.go:371 +0xf2 fp=0xc000495bc0 sp=0xc000495b20 pc=0x55be22
encoding/gob.encOpFor.func3(0xc0004fe720, 0xc0006da0c0, 0x78f900, 0xc00019e1b0, 0x15)
	/usr/local/go/src/encoding/gob/encode.go:571 +0xa7 fp=0xc000495c40 sp=0xc000495bc0 pc=0x566c07
encoding/gob.(*Encoder).encodeSingle(0xc00038a1e0, 0xc00038a218, 0xc00034d8c0, 0x78f900, 0xc00019e1b0, 0x15)
	/usr/local/go/src/encoding/gob/encode.go:301 +0x185 fp=0xc000495c98 sp=0xc000495c40 pc=0x55b465
encoding/gob.(*Encoder).encode(0xc00038a1e0, 0xc00038a218, 0x78f900, 0xc00019e1b0, 0x15, 0xc0001bc3c0)
	/usr/local/go/src/encoding/gob/encode.go:703 +0x182 fp=0xc000495d08 sp=0xc000495c98 pc=0x55ef22
encoding/gob.(*Encoder).EncodeValue(0xc00038a1e0, 0x78f900, 0xc00019e1b0, 0x15, 0x0, 0x0)
	/usr/local/go/src/encoding/gob/encoder.go:251 +0x3aa fp=0xc000495da8 sp=0xc000495d08 pc=0x56052a
encoding/gob.(*Encoder).Encode(0xc00038a1e0, 0x78f900, 0xc00019e1b0, 0x4, 0xc0004b0060)
	/usr/local/go/src/encoding/gob/encoder.go:176 +0xa6 fp=0xc000495df8 sp=0xc000495da8 pc=0x55ff66
github.com/miguelmota/cointop/cointop/common/filecache.serialize(0x78f900, 0xc00019e1b0, 0x0, 0x0, 0x30, 0xc0004b0000, 0x2b)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/common/filecache/filecache.go:115 +0x6d fp=0xc000495e38 sp=0xc000495df8 pc=0x56b06d
github.com/miguelmota/cointop/cointop/common/filecache.Set(0xc00010b580, 0x19, 0x78f900, 0xc00019e1b0, 0x4e94914f0000, 0x0, 0x0)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/common/filecache/filecache.go:28 +0x287 fp=0xc000495f10 sp=0xc000495e38 pc=0x56a507
github.com/miguelmota/cointop/cointop.(*Cointop).updateCoins(0xc000143880, 0x0, 0x0)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/list.go:41 +0x2ad fp=0xc000495fb0 sp=0xc000495f10 pc=0x728d8d
github.com/miguelmota/cointop/cointop.(*Cointop).layout.func3(0xc000143880)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/layout.go:79 +0x2b fp=0xc000495fd8 sp=0xc000495fb0 pc=0x735c6b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000495fe0 sp=0xc000495fd8 pc=0x459881
created by github.com/miguelmota/cointop/cointop.(*Cointop).layout
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/layout.go:78 +0x546

goroutine 1 [select]:
github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop(0xc000280000, 0xc000280000, 0x0)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui/gui.go:371 +0x17b
github.com/miguelmota/cointop/cointop.(*Cointop).Run(0xc000143880)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/cointop.go:330 +0x23d
github.com/miguelmota/cointop/cmd.Run()
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cmd/cointop.go:36 +0x60a
main.main()
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/main.go:8 +0x20

goroutine 20 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 24 [select]:
github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache.(*janitor).Run(0xc00019a110, 0xc0000e1d00)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0xd5
created by github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache.runJanitor
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xa9

goroutine 3 [select]:
github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go.Init.func1()
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go/api.go:95 +0x332
created by github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go.Init
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go/api.go:92 +0x739

goroutine 5 [select]:
github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/nsf/termbox-go/api.go:339 +0x22e
github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop.func1(0xc000280000)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui/gui.go:354 +0x30
created by github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui.(*Gui).MainLoop
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/vendor/github.com/jroimartin/gocui/gui.go:352 +0x57

goroutine 11 [select]:
github.com/miguelmota/cointop/cointop.(*Cointop).intervalFetchData.func1(0xc000143880)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/layout.go:191 +0xa9
created by github.com/miguelmota/cointop/cointop.(*Cointop).intervalFetchData
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/layout.go:189 +0x3f

goroutine 157 [runnable]:
github.com/miguelmota/cointop/cointop.(*Cointop).processCoins(0xc000143880, 0xc00087c000, 0xfa, 0x12d)
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/list.go:65 +0x2cc
created by github.com/miguelmota/cointop/cointop.(*Cointop).updateCoins
	/home/sevenless/gocode/src/github.com/miguelmota/cointop/cointop/list.go:39 +0x210

goroutine 85 [IO wait]:
internal/poll.runtime_pollWait(0x7f55c5d3b1f0, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000338198, 0x72, 0x8b00, 0x8b73, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000338180, 0xc00051a000, 0x8b73, 0x8b73, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000338180, 0xc00051a000, 0x8b73, 0x8b73, 0x203000, 0x40ce99, 0xc0007f4060)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000de9a0, 0xc00051a000, 0x8b73, 0x8b73, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc00034c760, 0xc00051a000, 0x8b73, 0x8b73, 0xb32e20, 0x7f55c40be918, 0xc000093938)
	/usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0002a65d8, 0x88bf40, 0xc00034c760, 0x40afa5, 0x79f600, 0x7f0060)
	/usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0002a6380, 0x88c280, 0xc0000de9a0, 0x5, 0xc0000de9a0, 0x203000)
	/usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0002a6380, 0x828000, 0xc0002a64b8, 0xc000093b88)
	/usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0002a6380, 0xc0005f2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc00033e120, 0xc0005f2000, 0x1000, 0x1000, 0xc000093c88, 0x406725, 0xc0005eafc0)
	/usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0004e42a0)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0004e42a0, 0x1, 0x0, 0x0, 0x1, 0xc000019000, 0x0)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00033e120)
	/usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1357 +0xae8

goroutine 86 [select]:
net/http.(*persistConn).writeLoop(0xc00033e120)
	/usr/local/go/src/net/http/transport.go:1958 +0x113
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1358 +0xb0d

```

**Comment by miguelmota** [comment]
Thanks for the output logs guys. The error `fatal error: concurrent map iteration and map write` is useful enough to start debugging.

**Comment by oliverkane** [comment]
Lemme know if I can provide any other sort of output.  Not familiar with Go's dev ways, but I'd be happy to learn a thing or two.

**Comment by miguelmota** [comment]
Pushed a fix (https://github.com/miguelmota/cointop/commit/ca3921efb07b592bf9eda981deae32db54df0c6c). A new release should be available in the package managers after a day

**Comment by oliverkane** [comment]
It does change the behavior for me, but now it insta-crashes.  I've installed from source via the `go get` command and not from a package manager.  I'll be around today at the keys if you want more details.  

go version go1.12.3 linux/amd64

![image](https://user-images.githubusercontent.com/1761622/58751798-4d9bcf00-8469-11e9-9e5f-1c00f348e353.png)


![image](https://user-images.githubusercontent.com/1761622/58751783-12010500-8469-11e9-97ae-47822353f265.png)

**Comment by oliverkane** [comment]
I neglected the part where you mention to create a new issue. I'll do that.

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/issues/33
