### ISSUE TITLE
panic: runtime error: index out of range [7] with length 0

### ISSUE THREAD

**Issue by GideonWolfe** [miguelmota/cointop#44]
All that needs to happen to reproduce this error on my machine is:

1. Open cointop
2. Leave it alone for a few hours
3. Return. The app will have crashed with the following output:

``` 
~ λ cointop
panic: runtime error: index out of range [7] with length 0

goroutine 1 [running]:
github.com/jroimartin/gocui.(*View).Write(0xc0004100f0, 0xc00041e000, 0x9de, 0xa80, 0xc000465900, 0xc000465900, 0x555c389de05d)
	/home/gideon/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/view.go:224 +0x4e0
fmt.Fprint(0x555c390c21a0, 0xc0004100f0, 0xc000465968, 0x1, 0x1, 0x1, 0xc000650000, 0x9de)
	/usr/lib/go/src/fmt/print.go:233 +0x8d
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateChart.func1()
	cointop/chart.go:102 +0x14c
github.com/miguelmota/cointop/cointop.(*Cointop).update.func1(0xc0003dc000, 0xc0004659c0, 0x2)
	cointop/update.go:19 +0x26
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc0003dc000, 0xc0003dc000, 0x0)
	/home/gideon/go/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:377 +0x2db
github.com/miguelmota/cointop/cointop.(*Cointop).Run(0xc000170420, 0x0, 0x0)
	cointop/cointop.go:353 +0x355
github.com/miguelmota/cointop/cmd.Execute.func1(0xc00017a000, 0x555c3942c4c0, 0x0, 0x0, 0x0, 0x0)
	cmd/cointop.go:77 +0x249
github.com/spf13/cobra.(*Command).execute(0xc00017a000, 0xc0000201d0, 0x0, 0x0, 0xc00017a000, 0xc0000201d0)
	/home/gideon/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x462
github.com/spf13/cobra.(*Command).ExecuteC(0xc00017a000, 0xc0000a9f18, 0x5, 0x5)
	/home/gideon/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/gideon/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/miguelmota/cointop/cmd.Execute()
	cmd/cointop.go:152 +0xd56
main.main()
	main.go:8 +0x22
```

This is running in urxvt on Arch Linux

**Comment by lookfirst** [comment]
Similar... I just clicked on my terminal window.

brew installed on osx.

```
cointop
panic: runtime error: index out of range [9] with length 0

goroutine 1 [running]:
github.com/jroimartin/gocui.(*View).Write(0xc0002e20f0, 0xc0004cb000, 0x760, 0x800, 0xc0000dd900, 0xc0000dd900, 0x100b78b)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/pkg/mod/github.com/jroimartin/gocui@v0.4.0/view.go:224 +0x4de
fmt.Fprint(0x1621c80, 0xc0002e20f0, 0xc0000dd968, 0x1, 0x1, 0x1, 0xc00066f000, 0x760)
	/usr/local/Cellar/go/1.13/libexec/src/fmt/print.go:233 +0x8b
github.com/miguelmota/cointop/cointop.(*Cointop).UpdateChart.func1()
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/src/github.com/miguelmota/cointop/cointop/chart.go:102 +0x14a
github.com/miguelmota/cointop/cointop.(*Cointop).update.func1(0xc0002c4000, 0xc0000dd9c0, 0x2)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/src/github.com/miguelmota/cointop/cointop/update.go:19 +0x24
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc0002c4000, 0xc0002c4000, 0x0)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/pkg/mod/github.com/jroimartin/gocui@v0.4.0/gui.go:377 +0x2d9
github.com/miguelmota/cointop/cointop.(*Cointop).Run(0xc00021c160, 0x0, 0x0)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/src/github.com/miguelmota/cointop/cointop/cointop.go:353 +0x353
github.com/miguelmota/cointop/cmd.Execute.func1(0xc000224000, 0x19a7338, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/src/github.com/miguelmota/cointop/cmd/cointop.go:77 +0x247
github.com/spf13/cobra.(*Command).execute(0xc000224000, 0xc0000b6010, 0x0, 0x0, 0xc000224000, 0xc0000b6010)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000224000, 0xc0000ddf18, 0x5, 0x5)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/miguelmota/cointop/cmd.Execute()
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/src/github.com/miguelmota/cointop/cmd/cointop.go:152 +0xd54
main.main()
	/private/tmp/cointop-20190915-91511-10vamc4/cointop-1.3.6/src/github.com/miguelmota/cointop/main.go:8 +0x20
```

**Comment by miguelmota** [comment]
Thanks for the bug reports. A fix for this problem has been included in the latest release.
