### ISSUE TITLE
panic when running in termux

### ISSUE THREAD

**Issue by githorray** [miguelmota/cointop#62]
```
panic: mkdir /tmp: read-only file system

goroutine 1 [running]:
github.com/miguelmota/cointop/cointop/common/filecache.NewFileCache(0x40001f3a70, 0x5)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/miguelmota/cointop@v1.5.4/cointop/common/filecache/filecache.go:45 +0x160
github.com/miguelmota/cointop/cointop.NewCointop(0x40001f3c50, 0x5be5b5a6f6, 0xc, 0x0)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/miguelmota/cointop@v1.5.4/cointop/cointop.go:180 +0x1c24
github.com/miguelmota/cointop/cointop/cmd.RootCmd.func1(0x40001a6b00, 0x5be60008b0, 0x0, 0x0, 0x0, 0x0)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/miguelmota/cointop@v1.5.4/cointop/cmd/root.go:80 +0x1d0
github.com/spf13/cobra.(*Command).execute(0x40001a6b00, 0x40001121b0, 0x0, 0x0, 0x40001a6b00, 0x40001121b0)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x2f8
github.com/spf13/cobra.(*Command).ExecuteC(0x40001a6b00, 0x40001f3f18, 0x8, 0x8)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x24c
github.com/spf13/cobra.(*Command).Execute(...)
        /data/data/com.termux/files/home/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/miguelmota/cointop/cointop/cmd.Execute()
        /data/data/com.termux/files/home/go/pkg/mod/github.com/miguelmota/cointop@v1.5.4/cointop/cmd/cmd.go:22 +0xf4
main.main()
        /data/data/com.termux/files/home/go/pkg/mod/github.com/miguelmota/cointop@v1.5.4/main.go:8 +0x18
```

**Comment by miguelmota** [comment]
@githorray does the same panic happen if you run `cointop --no-cache`?

**Comment by githorray** [comment]
No, cointop starts normally with that option.

**Comment by miguelmota** [comment]
Thanks for checking. I think it's because termux has a non-standard directory hierarchy: https://wiki.termux.com/wiki/Differences_from_Linux

Will implement a fix later this week.

**Comment by githorray** [comment]
Great.

I also tried `cointop --cache-dir ~/.tmp`. It sort of works, but cointop does not expand out the `~` to the current home directory and you end up getting a folder named `~.` with the cache contents in the directory cointop was started from.

**Comment by miguelmota** [comment]
Interesting, does termux have the `HOME` env var set? you can check with `echo $HOME`

**Comment by githorray** [comment]
`$ echo $HOME
/data/data/com.termux/files/home`

**Comment by miguelmota** [comment]
@githorray changes made:

- soft fail (don't panic) if there is cache dir error. Proceed without cache.
- store cache dir preference in config file. Preference set with `--cache-dir` flag will write it to config.
- You can also edit config directly to add or modify preference:
    ```toml
    cache_dir = "/tmp"
    ```

I tried it out on termux with the following:

```
pkg install git
pkg install golang
go get github.com/miguelmota/cointop
cd ~/go/src/github.com/miguelmota/cointop
go run cm/cointop/cointop.go
```

**Comment by githorray** [comment]
working great. thanks.

**Comment by miguelmota** [comment]
Closed by https://github.com/miguelmota/cointop/commit/890e1c5704bca84dfca346cc451b863bb26905d7
